### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by jods4** [ast-grep/ast-grep#30] opened 2022-09-05 09:06 UTC
I would be really interested in using this tool with C# (`.cs`) code, any chance you can add it to the list of supported languages?
It has a treesitter parser: https://github.com/tree-sitter/tree-sitter-c-sharp
A C# identifier is not allowed to start with `$` so it'd work great (makes me wonder... how do you handle that in JS, where `$` is a valid identifier?)

I would also love if ast-grep could work with TS/JS code that is inside Vue SFC `.vue` files, but that might be more difficult as you'd need a `.vue` SFC parser to extract the `<script>` block(s) and figure out their `lang` attribute...

**Comment by HerringtonDarkholme** [comment] 2022-09-05 16:57
Hi Jods! Happy to see you interested in the project!

C# support is not too hard. The parser is already available and how much time integration will take depends on the parser's version and quality. (Worst scenario is to fork the original parser and publish another crate for it).

The identifier issue is not hard to solve though. Actually Rust has already implemented similar mechanism to replace meta variable char. https://github.com/HerringtonDarkholme/ast-grep/blob/main/crates/cli/src/languages/rust.rs#L14

**Comment by HerringtonDarkholme** [comment] 2022-09-05 16:59
`.vue` single file component format is definitely on the roadmap! Tree-sitter has the concept of multi-language document. So supporting `vue` should follow that pathway, though I'm not sure how straightforward it will be.

That said, multi-language document is not top priority for now.

**Comment by jods4** [comment] 2022-09-05 17:01
Awesome!

Note that Vue support might increase the importance of replacing the meta variable.
Vue has plans to add reactivity macros with many names starting with `$`, such as `$`, `$$`, `$ref`, `$computed` and more...

**Comment by jods4** [comment] 2022-09-05 17:11
> Worst scenario is to fork the original parser and publish another crate for it

Hopefully the C# parser is good enough, Treesitter homepage puts it in the "fairly complete" category, the parser itself says "Comprehensive supports C# 1 through 10.0" and I can see C#11 features are already implemented.

If it is not, sadly I doubt forking would be sustainable. C# is a big, complex language that is moving fairly quickly these days with lots of new features released each year. Maintaining a high-quality parser for C# is a lot of work.

**Comment by HerringtonDarkholme** [comment] 2022-09-06 00:37
C# initial support is added in 9a14a4b71cc348274ad6d153fc9011aedf9b490e.

**Comment by jods4** [comment] 2022-09-06 09:52
Another example of having a hard time matching code:
Given this source code:
```csharp
var predicate = new ExprExpr(Expr1, Operator, Expr2, null);
```

A full statement matches: `var predicate = new ExprExpr($$$);`

But any attempt at matching expressions fails, such as:
- `var predicate = new ExprExpr($$$)` (no colon)
- `new ExprExpr($$$)`
- `new ExprExpr($$$);` wasn't expecting this to change anything -- it did not :)
- `predicate = new ExprExpr($$$)` with or without colon. Not sure I expect this to work as the AST for a variable initializer might be different from a variable assignment...

**Comment by HerringtonDarkholme** [comment] 2022-09-06 17:56
Thanks for your valuable feedback! I'm not familiar with C# so your feedback is crucial for me to improve the tool!

I guess the problem is caused by missing semicolon: C# parser probably need it to be successfully parsed. I can try if they can be fixed.

**Comment by jods4** [comment] 2022-09-06 18:32
I have the impression that the query only work if they could be parsed as full programs, indeed.
That's just a guess, but nowadays with top level statements in `Program.cs`, these queries could well be full programs:
```csharp
ThrowHelper.ThrowArgumentNullException($);
var predicate = new ExprExpr($$$);
```

What doesn't 100% click is that this attempt could be a valid program as well:
```csharp
new ExprExpr($$$);
```
but for some reason that didn't match.

If you're not familiar with C#, at the syntax level you can think of it as of Java. They're super similar, superficially.

The C# treesitter parser README says:
> Support syntax highlighting/parsing of fragments

But I have no idea how that's supposed to work.

If you want to try to write C# code, check this out: 
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzggPgAQEwEYCwAUJrgJwAUARABICmANvQPaUCUA3EUTLQO4AEAUQAeAY1oAHBFCYxyHIA=

**Comment by HerringtonDarkholme** [comment] 2022-09-08 02:32
> Also on Windows, running sg without args (I was hoping for help, same as sg --help) panicks

Fixed in bffc0d4ebfb5e761c77cb6b4b79bc8c155133379

**Comment by tazjin** [comment] 2023-05-12 13:00
There's a mention on the homepage that says

> You can also register your own tree-sitter parsers by dynamic loading.

How does this work? It seems like some extra code is needed for most tree-sitter grammars?

I'd like to give adding support for Nix a try, we don't really have any good refactoring tooling in this style yet and it would be very useful.

**Comment by HerringtonDarkholme** [comment] 2023-05-12 16:48
@tazjin Thanks for your support!
Using custom language is much too complicated for average users and it is pretty experimental now. 

> How does this work? It seems like some extra code is needed for most tree-sitter grammars?
It is done by using tree-sitter parsers as dynamic library. No extra code is needed but you need to compile the lib yourself since there is probably no compiled lib on the internet for your OS/arch.

For reference, here is a simple how-to list:

1. Compile tree-sitter as dynamic library, see https://github.com/ast-grep/ast-grep/discussions/351
2. Register the language in sgconfig.yml
```yml
customLanguage:
  mojo:
      libraryPath: mojo.so # path to dynamic lib
      extensions: [mojo]
      # expandoChar: optional character to replace metavariable $ in your pattern
```
3. Now you can use it, `sg -p 'print("hello word")' -l mojo`


I plan to add a [document](https://github.com/ast-grep/ast-grep.github.io/issues/98).

**Comment by tazjin** [comment] 2023-05-13 15:38
Cool, thanks for the response!

I'm trying this out right now. We have a huge number of dynamic library versions of tree-sitter grammars in the Nix package set, but I can't quite get it to work yet.

sgconfig.yml:

```
ruleDirs:
  - rules
customLanguage:
  nix:
    libraryPath: /nix/store/wxkiwnj004ps1rp23pn7iz4yzypy1bnw-tree-sitter-nix-grammar-0.20.8/parser
    extensions: [nix]
```

That file is a dynamically linked tree-sitter grammar:
```
tazjin@tverskoy ~> nix-build -E "(import <nixpkgs> {}).tree-sitter-grammars.tree-sitter-nix"
/nix/store/wxkiwnj004ps1rp23pn7iz4yzypy1bnw-tree-sitter-nix-grammar-0.20.8
tazjin@tverskoy ~> file result/parser
result/parser: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
tazjin@tverskoy ~> ldd result/parser
        linux-vdso.so.1 (0x00007fff93508000)
        libstdc++.so.6 => /nix/store/shasq3azl2298vqkvq5mc7vivdqp3yrj-gcc-12.2.0-lib/lib/libstdc++.so.6 (0x00007f07c9628000)
        libm.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libm.so.6 (0x00007f07c9548000)
        libgcc_s.so.1 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libgcc_s.so.1 (0x00007f07c952e000)
        libc.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libc.so.6 (0x00007f07c9325000)
        /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib64/ld-linux-x86-64.so.2 (0x00007f07c9869000)
```

but it seems like the config is being ignored, or a misleading error is thrown:

```
tazjin@tverskoy /depot ((96c726c6))> /nix/store/d0xwr9agwn1q3ck15mwlvvigf2gipyws-ast-grep-0.4.1/bin/sg -p 'import' -l nix
error: invalid value 'nix' for '--lang <LANG>': nix is not supported!
```

Maybe that "invalid value" message is masking some error while loading the dynamic library? I haven't dug deeper (yet).

**Comment by HerringtonDarkholme** [comment] 2023-05-13 16:34
My bad! The config name is `customLanguages`. Note the plural noun!

**Comment by tazjin** [comment] 2023-05-13 17:03
I bumped to 0.5.1 and changed it to `customLanguages`, and now it works - very, very cool! I wrote some experimental Nix code to wrap it and generate config for the tree-sitter grammars we have in nixpkgs ([99 of them](https://gist.github.com/tazjin/c83f49d8b4ba4f6dee035fb929b4922c)!), and they all seem to work.

Some things seem a bit difficult to do in some languages, for example in Nix I quickly run into something like wanting to write a query against a node that has children, where _any child_ matches the thing I'm looking for (e.g. an attribute set literal like `{ a = 12; b = 42; }` where I'm looking for *any* of these that have e.g. `b = 42`. This is probably somewhat constrained by tree-sitter grammars also not having a uniform structure. Anyways, I digress.

I'd like to ship this in Nix(OS) with a helper function that lets people add the languages they need from our list of languages (is there any downside to just adding all languages right away, maybe minus the ones you already have included?). It would be nice if the binary could be wrapped in some way to provide a separate config file for languages (or just multiple config files in general). Imagine a "system-wide" language config which adds all the stuff I expect `sg` to know about, and then the project-local configs for rules etc. Is something like that maybe also possible already?

**Comment by HerringtonDarkholme** [comment] 2023-05-14 17:19
@tazjin Thanks for testing out! I appreciate your help!

> is there any downside to just adding all languages right away
Do you mean including all languages in the binary? That might make the binary too bloated. But I do think supporting more popular mainstream language is a priority.


> Imagine a "system-wide" language config
I got you. It is really convenient for a global default configuration and I am tempted to do so. But according to eslint's experience, https://eslint.org/blog/2022/08/new-config-system-part-2/, I would spend more time thinking about how config could be composed together.

> Some things seem a bit difficult to do in some languages, for example in Nix I quickly run into something like wanting to write a query against a node that has children, where any child matches the thing I'm looking

I think that should work with the relational rule config! https://ast-grep.github.io/guide/rule-config/relational-rule.html

**Comment by tazjin** [comment] 2023-05-14 17:32
> Do you mean including all languages in the binary?

Not necessarily in the binary of ast-grep itself, but in the package we expose in Nix/NixOS. It's essentially a program with 'plugins', and often (for programs like e.g. `ffmpeg`) we'll have a "light" (default) and a "full" version (with all plugins). We could expose an `astGrepFull` package to users with all languages supported by tree-sitter. I'm just wondering if that would have any practical downsides other than size (e.g. scanning speed).

> So currently we don't have anything like global config.

Yeah, it's hard to decide on the semantics for that. I'd do something like have a `--config-file` option that *prepends* config files to load to whatever is in the project directory, and then the type would need to implement specific merging logic. I might write a small experimental patch to do this just for our use-case and see how it works, but I would only do it for the `customLanguages` field for now.

**Comment by HerringtonDarkholme** [comment] 2023-05-26 22:57
@tazjin 
> have a --config-file option that prepends config files to load to whatever is in the project directory

I think `scan` command already support the `--config` argument. 

<img width="1211" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/810f664f-df57-439c-bab5-9ff7d0f18377">

**Comment by HerringtonDarkholme** [comment] 2023-05-26 23:04
I'm going to close this issue to favor https://github.com/ast-grep/ast-grep/discussions/419. If you need to discuss we can move there.

**Closed by HerringtonDarkholme** 2023-05-26 23:04 UTC

**Comment by n8henrie** [comment] 2024-06-07 19:42
@tazjin any progress on a nixpkgs ast-grep with built-in nix support?
