### ISSUE TITLE
sg command conflicts with sg from shadow-utils

### ISSUE THREAD

**Issue by andrewshadura** [ast-grep/ast-grep#706] opened 2023-11-08 08:25 UTC
Please rename or drop the `sg` shortcut for the `ast-grep` command-line tool.

`sg` is a command-line tool to execute a command as different group ID, similar to `newgrp` but accepting a command. It is part of shadow-utils project and is shipped in base system in many distributions, e.g. in Debian in the `login` package.

See https://manpages.debian.org/testing/login/sg.1.en.html for more details about it.

**Comment by HerringtonDarkholme** [comment] 2023-11-08 08:33
This is already discussed in https://github.com/ast-grep/ast-grep/issues/56 and pinned at the top of the issue list.

**Comment by andrewshadura** [comment] 2023-11-08 08:36
Wow, I didn’t see it at all, apparently it’s the result of the ad blindness 🙂

**Comment by andrewshadura** [comment] 2023-11-08 08:38
Since that issue was filed back in May, maybe it’s the time to update the documentation and remove all mentions of `sg` (replacing them with `ast-grep`)?

**Comment by HerringtonDarkholme** [comment] 2023-11-08 08:41
Thanks for the suggestion! We have noticed that before, so a warning tip has already been added to the installation part.

https://ast-grep.github.io/guide/quick-start.html#installation

**Comment by HerringtonDarkholme** [comment] 2023-11-15 23:58
Closed as duplicate of #56

**Closed by HerringtonDarkholme** 2023-11-15 23:58 UTC
Labels: bug
