### ISSUE TITLE
[ Bug ] parseFiles callback is called after the returning promise is resolved

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#206] opened 2023-01-26 09:14 UTC
## Summary
callback of `parseFiles` is called even after `parseFiles` promise is resolved.

## Reproduction repo 
https://github.com/ShenQingchuan/repro-sg-parse-files-0.2.2

## Reproduction

You could see this kind of output in reproduction:

```txt
File: /workspace/repro-sg-parse-files/src/mockFiles/test-file-7304-7bf21e37-8fda-473d-8d0f-74804dd95620.js - Run callback
File: /workspace/repro-sg-parse-files/src/mockFiles/test-file-7303-9f5f76c6-b72f-46bf-a2b7-1c1e01c01a56.tsx - Run callback
File: /workspace/repro-sg-parse-files/src/mockFiles/test-file-7302-d89a12ba-0e94-4e3f-bd95-a0b3ff1fca4e.tsx - Run callback
File: /workspace/repro-sg-parse-files/src/mockFiles/test-file-7301-c85276ef-f257-4563-bc63-74ca8084f8ec.js - Run callback
File: /workspace/repro-sg-parse-files/src/mockFiles/test-file-7300-649fcf13-ce01-4f6f-900b-da37d249b6ca.tsx - Run callback

 --- Main Function Over ---

/workspace/repro-sg-parse-files/src/mockFiles/test-file-9999-5113bbf8-4df2-4bde-b3de-3f13155ede8a.tsx == Imports ==>
/workspace/repro-sg-parse-files/src/mockFiles/test-file-9998-eadc0534-fc86-4a20-acd7-e95d60410f31.ts == Imports ==> './dynamic-plain-65/some-file-1', './dynamic-plain-34/some-file-2', './dynamic-plain-43/some-file-3'
```

the async function `runAstGrepParse` is not worked as expected, it should end after every callback function synchronously executed.

## Issue cause
> Limit maximum synchronous iteration count to prevent event loop
> starvation. See `src/node_messaging.cc` for an inspiration.

https://github.com/nodejs/node/blob/8ba54e50496a6a5c21d93133df60a9f7cb6c46ce/src/node_api.cc#L336

**Comment by HerringtonDarkholme** [comment] 2023-01-26 09:45
Thanks for the reporting and the detailed reproduction! It is very helpful!

I have found the root cause of the problem. Sorry to introduce this bug due to my limited understanding of Napi and NodeJS.

Here is the detailed walk through of this bug. I hope it can help you.

-----

# Background

The `parseFiles` in ast-grep is implemented by napi-rs' [thread safe function](https://napi.rs/docs/concepts/threadsafe-function). Its behavior is more detailed documented [here](https://napi.inspiredware.com/special-topics/thread-safe-functions.html#Thread-Management).

The crux of the problem is that calling thread safe function in napi from Rust will not actually call the JavaScript function. Instead, the callback task is pushed to a queue as a record.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2883231/214801846-df7d68a5-e780-42a4-9de4-326374754b43.png">

# Issue 
I expect the `parseFiles` function call should be resolved only after all JS callbacks are executed. I suspected that pushing to the queue will not immediately call the JS function.
And the bug will be reproduced if Rust has pushed all files to the queue but NodeJS did not feed them to JavaScript. However, when I tried to reproduce the issue by increasing the execution time of the callback, the issue cannot be reproduced, no matter how long I synchronously sleep.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/2883231/214803737-b52b8852-5b8a-40cf-9b1b-61cc16f8db2f.png">


So when will the queue execution be yielded?

# Investigation
I investigated the `BlockingCall` API. It looks like the function just call the C API: [`napi_call_threadsafe_function`](https://github.com/nodejs/node-addon-api/blob/78b5a1553332d3a28e762c794a2d3bb131aef264/napi-inl.h#L5684).
And that function will eventually call the [`Push`](https://github.com/nodejs/node/blob/8ba54e50496a6a5c21d93133df60a9f7cb6c46ce/src/node_api.cc#L217-L236) method of `ThreadSafeFunction`, which looks totally innocent.
<img width="577" alt="image" src="https://user-images.githubusercontent.com/2883231/214802957-05be0774-eb75-435f-907a-e3ea29f95a75.png">

# Further Repro
I tried another way to reproduce the issue by reducing the file items. Curiously, the returning promise almost always stop when file count is 999.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/2883231/214803253-861caf3f-cecb-4522-845a-3ac259f2e797.png">

It probably means that NodeJS will suspend the callback execution when item count reaches 1000. So I "GitHub Search"ed the NodeJS core. Fortunately the `1000` magic number has only a few [matching](https://github.com/nodejs/node/blob/8ba54e50496a6a5c21d93133df60a9f7cb6c46ce/src/node_api.cc#L336) [hit](https://github.com/nodejs/node/blob/8ba54e50496a6a5c21d93133df60a9f7cb6c46ce/src/node_api.cc#L485).

Indeed! NodeJS' event loop will not drain the sync task queue!

<img width="550" alt="image" src="https://user-images.githubusercontent.com/2883231/214804461-ef7c1847-3e84-462b-a0ea-9d1cfb360097.png">

After 1000 files are processed by JavaScript, NodeJS will take a break to make event loop progress. But Rust will ruthlessly push all files to the queue. And the `parseFile` promise will resolve immediately after all files are pushed while files are still in the message queue awaiting JS callback.

**Comment by HerringtonDarkholme** [comment] 2023-01-26 15:52
Fixed in https://github.com/ast-grep/ast-grep/commit/ac266dbb3fdb8753e6bc66bc41519ec5deac4bda

**Closed by HerringtonDarkholme** 2023-01-26 15:52 UTC

**Comment by evangalen** [comment] 2024-02-01 18:33
I'm a bit confused about the fact that this issue is `Closed` whereas the documentatiom of `findInFiles` still refers to this issue as if it's not fixed.

![Screenshot_20240201_193027_Brave](https://github.com/ast-grep/ast-grep/assets/1895520/11caf743-3061-476c-a744-a5cd2f603a59)

**Comment by HerringtonDarkholme** [comment] 2024-02-01 18:46
This is not fixable in JavaScript world. Nothing to do from our side so the issue is closed.
