### ISSUE TITLE
[bug] Query with single colon fails, double colon never ends, uses 100% CPU

### ISSUE THREAD

**Issue by arathunku** [ast-grep/ast-grep#713] opened 2023-11-12 15:25 UTC
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVieSIsInF1ZXJ5IjoiRm9vOjokJE1PRFVMRSIsInJld3JpdGUiOiIkTU9EVUxFOjpGb28iLCJjb25maWciOiIjIFlBTUwgUnVsZSBpcyBtb3JlIHBvd2VyZnVsIVxuIyBodHRwczovL2FzdC1ncmVwLmdpdGh1Yi5pby9ndWlkZS9ydWxlLWNvbmZpZy5odG1sI3J1bGVcbnJ1bGU6XG4gIGFueTpcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUubG9nKCRBKVxuICAgIC0gcGF0dGVybjogY29uc29sZS5kZWJ1ZygkQSlcbmZpeDpcbiAgbG9nZ2VyLmxvZygkQSkiLCJzb3VyY2UiOiJtb2R1bGUgRm9vXG4gIG1vZHVsZSBCYXJcbiAgICBkZWYgc2VsZi5iYXpcbiAgICBlbmRcbiAgZW5kXG5lbmRcbkZvbzo6QmFyLmJheigpXG4ifQ==)

![image](https://github.com/ast-grep/ast-grep/assets/749393/6337676f-eab5-4f5b-a68d-b1b61ad0dbc1)

# 💻 Code

Code:

```ruby
# test.rb
module Foo
  module Bar
    def self.baz
    end
  end
end
Foo::Bar.baz()
```

Pattern:

- `Foo:`
- `Foo::`
- `Foo::$MODULE`

```sh
$ time sg -p 'Foo::$$MODULE' --lang ruby ./test.rb
^C
________________________________________________________
Executed in   32.54 secs    fish           external
   usr time   34.57 secs  984.00 micros   34.57 secs
   sys time    2.11 secs  137.00 micros    2.11 secs
```

```sh
$ sg --version
ast-grep 0.12.5
```

# 🙁 Actual behavior

For pattern `Foo:`, I get an error about query, which is expected, I see ERROR on playground too.

For pattern `Foo::` and `Foo::$MODULE`, I see a spike on multiple threads, 100% CPU usage and it never finishes.

# 🙂 Expected behavior

I expected all queries to finish quickly and valid (by playground) queries to match correctly.  I may be doing something wrong in the pattern, but if so - it's unclear to me what exactly and I guess hanging program is not expected.

If you have any pointers where to look for first, I think I can try submitting PR with a fix :smile:

**Comment by HerringtonDarkholme** [comment] 2023-11-14 01:26
Thanks! This is a valid bug! I will look at it soon!

**Comment by HerringtonDarkholme** [comment] 2023-11-15 20:50
It is caused by tree-sitter-ruby wrongly treating a leaf node as the root node, which in turns causes panic in tree traversal.

Thanks for reporting! It is fixed now!

**Closed** 2023-11-15 20:49 UTC
Labels: bug

**Comment by arathunku** [comment] 2023-11-16 07:30
@HerringtonDarkholme, thank you for the fix, I can confirm it no longer hangs! :)

If you have a moment more, I'm just unsure about the results for the queries, they look wrong

```sh
$ cat --plain /tmp/test.rb
module Foo
  module Bar
    def self.baz
    end
  end
end
Foo::Bar.baz()

$ sg -p 'Foo::Bar' --lang ruby /tmp/test.rb # ALL OK!
/tmp/test.rb
7│Foo::Bar.baz()


$ sg -p 'Foo::' --lang ruby /tmp/test.rb # !!! returns nothing
~

$ sg -p 'Foo::$MOD' --lang ruby /tmp/test.rb # !!! returns nothing

**Comment by HerringtonDarkholme** [comment] 2023-11-16 08:41
@arathunku  `Foo::$MOD` is parsed as  call expression
```
Pattern TreeSitter ("_call") receiver: (constant) method: (identifier)
```

while `Foo::Bar` is parsed as scope resolution

```
Pattern TreeSitter (scope_resolution scope: (constant) name: (constant))
```

Looks like the ruby tree-sitter has changed its parsing strategy...
